[2024/08/07 18:44:54]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:48:47]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:49:19]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:50:00]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/07 18:50:00]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/07 18:50:17]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/07 18:50:17]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/07 18:50:17]::[WARNING]::[django.request]=> (Bad Request: /pong/api/register/)
[2024/08/07 18:50:17]::[WARNING]::[django.request]=> (Bad Request: /pong/api/register/)
[2024/08/07 18:51:36]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:51:39]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:51:39]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:51:39]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:51:39]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:51:52]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:51:52]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:51:53]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:51:53]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:52:03]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:52:03]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:52:04]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:52:04]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/07 18:52:19]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:52:19]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/07 18:54:23]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/models.py changed, reloading.)
[2024/08/07 18:54:24]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:54:26]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/models.py changed, reloading.)
[2024/08/07 18:54:27]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:57:47]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 18:57:48]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:58:46]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:58:49]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:58:49]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:58:49]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 18:58:49]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 18:59:11]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 18:59:13]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:59:16]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:59:16]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:59:30]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 18:59:31]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 18:59:32]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:59:32]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 18:59:53]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 18:59:54]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:00:30]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 19:00:30]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[2024/08/07 19:00:31]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 19:00:31]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 19:01:33]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 17: 'path'. Did you forget to register or load this tag?
[2024/08/07 19:01:33]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 17: 'path'. Did you forget to register or load this tag?
[2024/08/07 19:01:33]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 19:01:33]::[WARNING]::[django.request]=> (Not Found: /favicon.ico)
[2024/08/07 19:01:42]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 19:01:43]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:01:53]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/urls.py changed, reloading.)
[2024/08/07 19:01:55]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:33:50]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:33:50]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:35:03]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/settings.py changed, reloading.)
[2024/08/07 19:35:04]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:41:50]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/nat/.local/lib/python3.8/site-packages/django/templatetags/i18n.py", line 329, in do_get_current_language
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'get_current_language' requires 'as variable' (got ['get_current_language'])
[2024/08/07 19:41:50]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/nat/.local/lib/python3.8/site-packages/django/templatetags/i18n.py", line 329, in do_get_current_language
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'get_current_language' requires 'as variable' (got ['get_current_language'])
[2024/08/07 19:42:25]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_language()'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 40: 'get_current_language()'. Did you forget to register or load this tag?
[2024/08/07 19:42:25]::[ERROR]::[django.request]=> (Internal Server Error: /pong/)
Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_language()'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/nat/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nat/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py", line 25, in base_view
    return render(request, 'pong/base.html')
  File "/home/nat/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/nat/.local/lib/python3.8/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 40: 'get_current_language()'. Did you forget to register or load this tag?
[2024/08/07 19:44:44]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py changed, reloading.)
[2024/08/07 19:44:45]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:44:49]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py changed, reloading.)
[2024/08/07 19:44:50]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:45:02]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py changed, reloading.)
[2024/08/07 19:45:03]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:45:06]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/views/auth_views.py changed, reloading.)
[2024/08/07 19:45:07]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:51:38]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/context_variables_processors.py changed, reloading.)
[2024/08/07 19:51:39]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:54:22]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/settings.py changed, reloading.)
[2024/08/07 19:54:22]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:54:24]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/settings.py changed, reloading.)
[2024/08/07 19:54:25]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:54:47]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:54:48]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:55:03]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:55:04]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:56:16]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:56:17]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:56:34]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:56:35]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:56:52]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/settings.py changed, reloading.)
[2024/08/07 19:56:53]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 19:58:48]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/07 19:58:49]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/07 20:05:09]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:05:09]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:14:56]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:14:56]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:11]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:11]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:14]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:14]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:17]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:17]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:22]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:22]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:29]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:29]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:47]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:15:47]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:16:09]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:16:09]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:16:57]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:16:57]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:17:17]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:17:17]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:17:26]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:17:26]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:18:05]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:18:05]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:18:21]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:18:21]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:20:33]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:20:33]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:20:54]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:20:54]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:01]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:01]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:23]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:23]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:26]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:26]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:31]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:21:31]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:24:39]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:24:39]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:24:41]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:24:41]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/07 20:24:49]::[INFO]::[pong.decorators.Logging]=> ((from : [logout_view]))
[2024/08/07 20:24:49]::[INFO]::[pong.decorators.Logging]=> ((from : [logout_view]))
[2024/08/08 12:39:26]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:39:37]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:39:37]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:39:38]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/08 12:39:38]::[WARNING]::[django.request]=> (Unauthorized: /pong/api/login/)
[2024/08/08 12:39:52]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/08 12:39:52]::[INFO]::[pong.decorators.Logging]=> ((from : [register_view]))
[2024/08/08 12:39:52]::[WARNING]::[django.request]=> (Bad Request: /pong/api/register/)
[2024/08/08 12:39:52]::[WARNING]::[django.request]=> (Bad Request: /pong/api/register/)
[2024/08/08 12:40:00]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:40:00]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:40:05]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:40:05]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 12:43:47]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:43:48]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:43:52]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:43:53]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:43:56]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:43:56]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:44:16]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:44:16]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:45:11]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:45:11]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:47:34]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:47:35]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:47:52]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:47:53]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:47:57]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:47:58]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:47:59]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:47:59]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:48:59]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:48:59]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:49:52]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:49:52]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:49:57]::[WARNING]::[django.request]=> (Not Found: /i18n/setlang/)
[2024/08/08 12:49:57]::[WARNING]::[django.request]=> (Not Found: /i18n/setlang/)
[2024/08/08 12:51:39]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:51:40]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 12:51:57]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:51:57]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:52:07]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:52:07]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:52:15]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:52:15]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 12:58:57]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 12:58:58]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 13:01:23]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:01:23]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:01:33]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:01:33]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:06:38]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:06:38]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:06:46]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:06:46]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 13:57:52]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/server/urls.py changed, reloading.)
[2024/08/08 13:57:52]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 14:10:05]::[INFO]::[pong.decorators.Logging]=> ((from : [logout_view]))
[2024/08/08 14:10:05]::[INFO]::[pong.decorators.Logging]=> ((from : [logout_view]))
[2024/08/08 14:10:13]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 14:10:13]::[INFO]::[pong.decorators.Logging]=> ((from : [login_view]))
[2024/08/08 14:10:25]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 14:10:25]::[WARNING]::[django.request]=> (Not Found: /pong/undefined)
[2024/08/08 14:19:47]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/decorators/Logging.py changed, reloading.)
[2024/08/08 14:21:26]::[INFO]::[django.utils.autoreload]=> (Watching for file changes with StatReloader)
[2024/08/08 14:22:52]::[INFO]::[django.utils.autoreload]=> (/home/nat/project/Transe-en-dance/backend/project/pong/forms.py changed, reloading.)
